# Changes here will be overwritten by Copier

_commit: 0.1.7
_src_path: git@bbpgitlab.epfl.ch:neuromath/python-template.git
author_email: ''
author_name: Blue Brain Project, EPFL
copyright_license: GNU General Public License v3.0
copyright_year: '2022'
download_url: git@github.com:BlueBrain/diameter-synthesis.git
init_git: false
maintainer: Alexis Arnaudon (@arnaudon)
package_name: diameter_synthesis
project_description: Diametrize cells.
project_name: diameter-synthesis
project_url: https://diameter-synthesis.readthedocs.io
repository: BlueBrain/diameter-synthesis
repository_provider: github
support_py37: false
team_name: ''
today: 29 August 2022
tracker_url: https://github.com/BlueBrain/diameter-synthesis/issues
version: 0.5.1

# End of Copier answers
